hw2
sslanss/java-course-2023 pull request #3
Opened 2023-10-22 20:54 UTC by sslanss

2023-10-22 22:10 UTC, kkmikhaylova requested changes

2023-10-22 22:10 UTC, kkmikhaylova commented on project-template/src/main/java/edu/project1/dictionaries/AnimalsDictionary.java
> +public class AnimalsDictionary implements Dictionary {
Нужно убрать из этого PR логику другого задания, оставь здесь только вторую домашку, плиз

2023-10-22 22:10 UTC, kkmikhaylova commented on project-template/src/main/java/edu/hw2/task2/Square.java
> +        return super.setWidth(width);
Можно не переопределять метод в таком случае, он ведь аналогичен по логике

2023-10-22 22:10 UTC, kkmikhaylova commented on project-template/src/main/java/edu/hw2/task3/DefaultConnectionManager.java
> +    private double stableConnectionChance;
Неиспользуемая переменная, можно удалить

2023-10-22 22:10 UTC, kkmikhaylova commented on project-template/src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        if (successedAttempts < currentAttempts) {
Мы в таком случае выбросим исключение при наличии хотя бы одного неуспешного прохода, хотя если соединение всё-таки установилось (даже если не с первой попытке), то это успешная ситуация.
Здесь можно добавить внутрь try выход из метода с помощью return, в таком случае в этой строке окажемся только если точно не установили успешное соединение за заданное число попыток и условие в этой строке можно будет удалить

2023-10-23 22:54 UTC, kkmikhaylova requested changes

2023-10-23 22:54 UTC, kkmikhaylova commented on project-template/src/main/java/edu/project1/dictionaries/AnimalsDictionary.java
> -package edu.project1.dictionaries;
Вот тут всё ещё светятся файлы из проекта, причём если вмерджишь этот PR, то удалишь проект из main ветки. Можешь их в этой ветке заново создать и запушить, тогда они перестанут тут отображаться в качестве изменений. С тестами аналогично

2023-10-24 07:45 UTC, sslanss commented on project-template/src/main/java/edu/project1/dictionaries/AnimalsDictionary.java
> -package edu.project1.dictionaries;
правильно я понимаю, что нужно создать ещё один коммит с файлами проекта и именно в этот PR его добавить??

2023-10-24 09:53 UTC, sslanss commented on project-template/src/main/java/edu/project1/dictionaries/AnimalsDictionary.java
> -package edu.project1.dictionaries;
попыталась сделать как вы сказали, все равно файлы проекта отображаются....

2023-11-05 17:24 UTC, kkmikhaylova approved these changes
Комменты всё равно остались, но ок

2023-11-07 16:59 UTC, merged