hw3
sslanss/java-course-2023 pull request #4
Opened 2023-10-29 18:52 UTC by sslanss

2023-11-05 21:04 UTC, Keindel requested changes
Для удобства я бы предложил повторить структуру пакетов в test.
Для тестов предлагаю применить @ParameterizedTest https://www.baeldung.com/parameterized-tests-junit-5

2023-11-05 21:04 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task2/BracesClasterizer.java
> +public final class BracesClasterizer {
BracesCl**u**sterizer

2023-11-05 21:04 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task2/BracesClasterizer.java
> +        } else {
Можно убрать else, тк в первом условии метод завершится.

2023-11-05 21:04 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task2/BracesClasterizer.java
> +                    isStringCorrect = false;
Если строка некорректна, то можно сразу заканчивать. Или тут другое имеется в виду?

2023-11-05 21:04 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task2/BracesClasterizer.java
> +                    countOpen--;
Кажется countOpen может быть отрицательной. Как обработается случай ")))((("?

2023-11-05 21:04 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task5/Contact.java
> +        String[] fullname = string.split(" ");
Лучше логику вынести из конструктора в другие методы.

2023-11-10 22:38 UTC, sslanss commented on project-template/src/main/java/edu/hw3/task5/Contact.java
> +        String[] fullname = string.split(" ");
не поняла вас, каким образом, если поля name и surname объявлены как final?

2023-11-10 22:44 UTC, sslanss commented on project-template/src/main/java/edu/hw3/task5/Contact.java
> +        String[] fullname = string.split(" ");
> Лучше логику вынести из конструктора в другие методы.

а как это сделать, если переменные объявлены как final и должны быть инициализированы в конструкторе? в другом методе возвращать список из двух элементов, потом присваивать в конструкторе? и исключение тоже я могу только в конструкторе выбросить, чтобы не создавать невалидный объект

2023-11-10 22:55 UTC, sslanss commented on project-template/src/main/java/edu/hw3/task2/BracesClasterizer.java
> +        } else {
> Можно убрать else, тк в первом условии метод завершится.

это принципиальный момент и , возможно, влияет на производительность? я привыкла так писать в учебном коде,  мне так более понятно..

2023-11-11 11:51 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task2/BracesClasterizer.java
> +        } else {
Это касается читаемости кода.
Принципиальным сейчас не является.

2023-11-11 12:00 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task5/Contact.java
> +        String[] fullname = string.split(" ");
Если будет отдельный метод в этом классе, вызываемый из конструктора - на данном этапе ок.
На мой взгляд, лучше-всего логику обработки строки вынести из класса Contact. Чтобы он не отвечал за обработку внешних данных для создания своего экземпляра. Дополнительное полезное чтение https://www.baeldung.com/solid-principles

2023-11-11 12:02 UTC, Keindel commented on project-template/src/main/java/edu/hw3/task5/Contact.java
> +        String[] fullname = string.split(" ");
Кстати, должны ли быть переменные final?

2023-11-13 07:07 UTC, Keindel approved these changes

2023-11-13 11:12 UTC, merged