hw4
sslanss/java-course-2023 pull request #5
Opened 2023-11-05 13:56 UTC by sslanss

2023-11-11 21:58 UTC, Keindel requested changes

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +            if (k <= animals.size()) {
достаточно этого
```
                return animals.stream()
                    .sorted(Comparator.comparingInt(Animal::weight).reversed())
                    .limit(k)
                    .toList();
```
проверять `k <= animals.size()` нет необходимости

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +            .collect(Collectors.toMap(Animal::type, animal -> animal, (animal1, animal2) -> {
можно использовать Function.identity() вместо  animal -> animal
и BinaryOperator.maxBy вместо сложной лямбды

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +                .limit(k)
попробуй .skip(k-1).findFirst()

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +            .filter(animal -> (animal.bites() && animal.height() > 100))
100 лучше вынести в константу или в параметр метода

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +                String[] words = animal.name().split(" ");
попробуй строку `"      word"`

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +            .sorted(Comparator.comparing(Animal::type).thenComparing(Animal::sex).thenComparing(Animal::name))
для читаемости лучше каждое следующее сравнение сделать на новой строке

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +                && animal.bites())
лучше animal.bites() вынести в отдельный фильтр - для читаемости

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +            .flatMap(List::stream)
👍

2023-11-11 21:58 UTC, Keindel commented on project-template/src/main/java/edu/hw4/Validator.java
> +public class Validator {
Отдельный класс Validator это хорошо 👍

2023-11-12 13:59 UTC, sslanss commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +            .collect(Collectors.toMap(Animal::type, animal -> animal, (animal1, animal2) -> {
спасибо, узнала более красивое решение!

2023-11-15 18:00 UTC, Keindel approved these changes

2023-11-15 18:00 UTC, Keindel commented on project-template/src/main/java/edu/hw4/AnimalTaskSolver.java
> +                String[] words = animal.name().split("\\s+");
Отлично! :+1:

2023-11-15 20:03 UTC, merged